/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/pmBH9wj27is
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Button } from "@/components/ui/button"
import { SVGProps } from 'react';

export function Aniweb() {
  return (
    <div className="bg-white min-h-screen flex flex-col items-center justify-center">
      <div className="bg-white rounded-lg shadow-lg p-8 max-w-4xl w-full">
        <header className="flex items-center justify-between mb-6">
          <nav className="flex space-x-6">
            <a href="#" className="text-lg font-semibold">
              Home
            </a>
            <a href="#" className="text-lg text-muted-foreground">
              About Us
            </a>
            <a href="#" className="text-lg text-muted-foreground">
              News
            </a>
            <a href="#" className="text-lg text-muted-foreground">
              Contact
            </a>
          </nav>
          <div className="relative">
            <input type="text" placeholder="Search" className="border rounded-full px-4 py-2" />
            <SearchIcon className="absolute right-3 top-2.5 h-5 w-5 text-muted-foreground" />
          </div>
        </header>
        <main className="flex items-center justify-between">
          <div className="space-y-4">
            <h1 className="text-5xl font-bold">Anime World</h1>
            <p className="text-muted-foreground">
              Explore the vibrant world of Japanese anime and immerse yourself in its captivating stories.
            </p>
            <Button variant="default">Discover Anime</Button>
          </div>
          <img
            src="/placeholder.svg"
            alt="Anime character"
            className="h-[400px] w-[300px] object-cover"
            width="300"
            height="400"
            style={{ aspectRatio: "300/400", objectFit: "cover" }}
          />
        </main>
      </div>
      <div className="bg-white rounded-lg shadow-lg p-8 mt-8 max-w-4xl w-full">
        <h2 className="text-3xl font-bold mb-4">Weekly Anime Schedule</h2>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <div className="space-y-2">
            <h3 className="text-xl font-semibold">Monday</h3>
            <ul className="list-disc list-inside">
              <li>Attack on Titan</li>
              <li>Demon Slayer</li>
              <li>My Hero Academia</li>
            </ul>
          </div>
          <div className="space-y-2">
            <h3 className="text-xl font-semibold">Tuesday</h3>
            <ul className="list-disc list-inside">
              <li>Jujutsu Kaisen</li>
              <li>Re:Zero</li>
              <li>Spy x Family</li>
            </ul>
          </div>
          <div className="space-y-2">
            <h3 className="text-xl font-semibold">Wednesday</h3>
            <ul className="list-disc list-inside">
              <li>Haikyuu!!</li>
              <li>Kaguya-sama: Love is War</li>
              <li>Vinland Saga</li>
            </ul>
          </div>
          <div className="space-y-2">
            <h3 className="text-xl font-semibold">Thursday</h3>
            <ul className="list-disc list-inside">
              <li>Chainsaw Man</li>
              <li>Mob Psycho 100</li>
              <li>Mushoku Tensei</li>
            </ul>
          </div>
          <div className="space-y-2">
            <h3 className="text-xl font-semibold">Friday</h3>
            <ul className="list-disc list-inside">
              <li>Boruto</li>
              <li>Fairy Tail</li>
              <li>One Piece</li>
            </ul>
          </div>
          <div className="space-y-2">
            <h3 className="text-xl font-semibold">Saturday</h3>
            <ul className="list-disc list-inside">
              <li>Naruto</li>
              <li>Re:Zero</li>
              <li>Sword Art Online</li>
            </ul>
          </div>
          <div className="space-y-2">
            <h3 className="text-xl font-semibold">Sunday</h3>
            <ul className="list-disc list-inside">
              <li>Dragon Ball Super</li>
              <li>Jojo's Bizarre Adventure</li>
              <li>Konosuba</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  )
}

function SearchIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}
