/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/TnLWuCw47HH
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Badge } from "@/components/ui/badge"
import { WeeklyAnimeSchedule } from "@/components/component/weekly-anime-schedule";
import { VideoPlayer } from "@/components/component/video-player";

export function MainPage() {
  return (
    <div className="min-h-screen bg-black text-white">
      <header className="flex items-center justify-between p-4">
        <div className="flex items-center space-x-4">
          <img src="/placeholder.svg" alt="Logo" className="h-8" />
          <div className="relative">
            <input
              type="text"
              placeholder="search Anime"
              className="pl-10 pr-4 py-2 bg-gray-800 rounded-full text-white"
            />
            <SearchIcon className="absolute left-3 top-2.5 h-5 w-5 text-gray-400" />
          </div>
        </div>
        <nav className="flex items-center space-x-6">
          <a href="#" className="text-yellow-500">
            Home
          </a>
          <a href="#">Anime List</a>
          <a href="#">New Seasons</a>
          <a href="#">Popular</a>
          <BellIcon className="h-6 w-6 text-white" />
          <Avatar>
            <AvatarImage src="/placeholder-user.jpg" alt="User Avatar" />
            <AvatarFallback>U</AvatarFallback>
          </Avatar>
        </nav>
      </header>
      <main className="p-4">
        <div className="flex space-x-4 ">
        <div className="flex-1">
          <div className="flex flex-col relative">
            <VideoPlayer />
            <div style={{marginLeft: '5vh' }} className="mt-4 text-white">
              <p className="text-sm">Home | TV</p>
              <h3 className="text-2xl font-bold">Jujutsu Kaisen</h3>
              <p className="text-sm">EP 24 • 24m</p>
              <div className="flex space-x-2 mt-2">
                <Badge variant="default">SUB</Badge>
                <Badge variant="default">HD</Badge>
                <Badge variant="default">DUB</Badge>
              </div>
            </div>
          </div>
        </div>
          <div className="w-1/3">
            <h2 className="text-yellow-500 mb-2">Episodes</h2>
            <div className="space-y-4">
              {[
                { title: "Episode 1", img: "/episode-1.jpg" },
                { title: "Episode 2", img: "/episode-2.jpg" },
                { title: "Episode 3", img: "/episode-3.jpg" },
                { title: "Episode 4", img: "/episode-4.jpg" },
                { title: "Episode 5", img: "/episode-5.jpg" },
              ].map((episode, index) => (
                <div key={index} className="flex items-center space-x-4 bg-gray-800 p-2 rounded-lg">
                  <img src="/placeholder.svg" alt={episode.title} className="w-12 h-16 rounded-lg" />
                  <div className="flex-1">
                    <h3 className="text-sm font-bold">{episode.title}</h3>
                    <div className="flex space-x-2 text-gray-400 text-xs mt-1">
                      <span>200,200</span>
                      <HeartIcon className="h-4 w-4" />
                      <span>200,200</span>
                      <EyeIcon className="h-4 w-4" />
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
        <div style={{ backgroundColor: '#e1b53e', marginTop: '5vh' }} className="p-4 rounded-lg flex items-center justify-center w-full">
          <div>
            <WeeklyAnimeSchedule/>
          </div>
        </div>
      </main>
    </div>
  )
}

function ArrowRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>
  )
}


function BellIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9" />
      <path d="M10.3 21a1.94 1.94 0 0 0 3.4 0" />
    </svg>
  )
}


function EyeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7-10-7-10-7Z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}


function HeartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}
